# -*- coding: utf-8 -*-
"""house_price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3eelpn8GY4H5mqSX5WNVIlmOOxadpg6
"""

# Importing the libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import pickle

df = pd.read_csv('https://raw.githubusercontent.com/9394113857/Data-Sets/a7ba0b540a02e3a0e06564365c9fd8730a60d382/house_price.csv')

df

plt.scatter(df['Area'],df['Price'])
plt.show()

x=df['Area'].values.reshape(-1,1)
y=df['Price'].values.reshape(-1,1)

lin = LinearRegression()
lin.fit(x,y)

pickle.dump(lin,open('house_price_linear_regression.pkl','wb'))

#loading the model
loaded_linear_regression_model = pickle.load(open("house_price_linear_regression.pkl", "rb"))

area=float(input("Please Enter Area Sq ft : "))
prediction_value = loaded_linear_regression_model.predict([[area]])
print("The Price Amount is : ",prediction_value, "Rupees")



# Downloading csv file:
csv_file = !gdown 1gakeZoKr6OGeuS5jb-BLj4X2j17O8IEz

print(type(csv_file))

# Downloading pickle file:
pickle_file = !gdown 1LDVk2mxKEPwf80Gv13d4xdAz-IKJP12I

print(type(pickle_file))

!pip install pickle

import pickle
#loading the model
loaded_linear_regression_model = pickle.load(open("house_price.pkl", "rb"))

area=float(input("Please Enter Area Sq ft : "))
prediction_value = loaded_linear_regression_model.predict([[area]])
print("The Price Amount is : ",prediction_value, "Rupees")

