# -*- coding: utf-8 -*-
"""iphone_price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nj8ePUHnyfsItYjxBFx8EloQJeZ-sstb
"""

# Importing the libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import pickle

"""#0.Downloading Any File From Google Drive:

Go to file change to public anyone acan access.

Copy link and select id from link and paste it.
"""

# downloaded_file = !gdown 1z64yPBIsFfQTxNS5dPtD9YVdCl67Jcu7
csv_file = !gdown 1z64yPBIsFfQTxNS5dPtD9YVdCl67Jcu7

# !gdown 1_3FVeyIEX31t96ya_6tSz0wjtX_UVg1a # This is id copy link and select id from link and paste link. Eg: '1_3FVeyIEX31t96ya_6tSz0wjtX_UVg1a'
downloaded_model = !gdown 1_3FVeyIEX31t96ya_6tSz0wjtX_UVg1a

"""#1.Upload the Data Set from Local System:"""

from google.colab import files
uploaded = files.upload()

"""#Load the dataset name:"""

# import io
# local_file = pd.read_csv(io.BytesIO(uploaded['iphone_price.csv']))

# local_file

"""#2.Load the Data Set from Google Drive:"""

# from google.colab import drive
# drive.mount("/content/gdrive")

# import pandas as pd
# drive_file = pd.read_csv('/content/gdrive/My Drive/iphone_price.csv')

# drive_file

"""#3.Load the Data Set from GitHub:"""

df = pd.read_csv('https://raw.githubusercontent.com/9394113857/Data-Sets/c45efacb19b01448b5a649a648a5469a37786f6b/iphone_price.csv')

df

plt.scatter(df['version'],df['price'])
plt.show()

linear_regression_model = LinearRegression()
linear_regression_model.fit(df[['version']],df[['price']])

iphone_version=float(input("Please Enter iphone_version : "))
prediction_value = linear_regression_model.predict([[iphone_version]])
print()
print(prediction_value)
print()
# dollar=float(input("Please Enter amount in dollars : "))
dollar = prediction_value
rupees=dollar*79.71
print("The Amount is : ",rupees, "Rupees")
print()





# Lets dump our model
pickle.dump(linear_regression_model, open('iphone_price_linear_regression.pkl','wb'))

#loading the model
loaded_linear_regression_model = pickle.load(open("iphone_price_linear_regression.pkl", "rb"))



iphone_version=float(input("Please Enter iphone_version : "))
prediction_value = loaded_linear_regression_model.predict([[iphone_version]])
print("The Dollar Amount is : ",prediction_value, "Dollars")
print("======================================")
# dollar=float(input("Please Enter amount in dollars : "))
dollar = prediction_value
rupees=dollar*79.71
print("The Amount is : ",rupees, "Rupees")
print("======================================")
print("======================================")

"""#===================================================================

# Getting error using dumped model while using from GitHub
"""

# import pickle
# #loading the model
# loading_dumped_model = pd.read_pickle('https://github.com/9394113857/Dumped_Models/blob/main/linear_regression_model.pkl')
# loaded_linear_regression_model = pickle.load(open(loading_dumped_model, "rb"))

"""#===================================================================

# File Download from google drive to colaboratory:

Reference:

https://stackoverflow.com/questions/48735600/file-download-from-google-drive-to-colaboratory

**No installing/importing any library. Just put your file id at the end.**

!gdown yourFileIdHere

Note: at the time of writing gdown library is preinstalled on Colab.
"""

# downloaded_file = !gdown 1z64yPBIsFfQTxNS5dPtD9YVdCl67Jcu7
csv_file = !gdown 1z64yPBIsFfQTxNS5dPtD9YVdCl67Jcu7

"""# This print statment will download the selected file to local system:"""

print(csv_file)

data_frame = pd.read_csv('iphone_price.csv')

data_frame

"""# Downloading Any File From Google Drive:"""

# !gdown 1_3FVeyIEX31t96ya_6tSz0wjtX_UVg1a # This is id copy link and select id from link and paste link. Eg: '1_3FVeyIEX31t96ya_6tSz0wjtX_UVg1a'
!gdown 1_3FVeyIEX31t96ya_6tSz0wjtX_UVg1a

import pickle
#loading the model
loaded_linear_regression_model = pickle.load(open("linear_regression_model.pkl", "rb"))

iphone_version=float(input("Please Enter iphone_version : "))
print("============================")
prediction_value = loaded_linear_regression_model.predict([[iphone_version]])
print("The Dollar Amount is : ",prediction_value, "Dollars")
print("============================")
# dollar=float(input("Please Enter amount in dollars : "))
dollar = prediction_value
rupees=dollar*79.71
print("The Amount is : ",rupees, "Rupees")
print("============================")
print()

